name = "goo"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["Empty"]

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v@leanVersion@"

[[require]]
name = "checkdecls"
git = "https://github.com/PatrickMassot/checkdecls.git"

[[require]]
name = "«doc-gen4»"
git = "https://github.com/leanprover/doc-gen4"
rev = "v@leanVersion@"

[[lean_lib]]
name = "Empty"
